services:
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/entrypoints/agent_entrypoint.sh"]
    volumes:
      - ./results:/results
    networks:
      - ros_docker_lstm_rossler_eval

  edge:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["/entrypoints/edge_entrypoint.sh"]
    volumes:
    - ./hyperparams.xlsx:/hyperparams.xlsx:ro
    networks:
      - ros_docker_lstm_rossler_eval

networks:
  ros_docker_lstm_rossler_eval:
    name: ros_lstm_rossler_eval
